version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - ./gradlew clean
  pre_build:
    commands:
      - echo "Pre-build phase starting ..."
      - ./gradlew compileJava
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Build phase starting ..."
      - ./gradlew build
      - echo "Build phase completed"
  post_build:
    commands:
      - echo "Post-build phase starting ..."
      - echo Starting MySQL Docker container for tests...
      - docker run --name mysql-test -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=testdb -d mysql:latest
      - ./gradlew test
      - echo Stopping MySQL Docker container...
      - docker stop mysql-test
      - docker rm mysql-test
      - echo "Post-build phase completed"

artifacts:
  files:
    - build/libs/**/*.jar
  discard-paths: yes