version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ""
    POSTGRES_TAG: 16.2
    DB_PASSWORD: ""
    ECR_REPO_PREFIX: ""
    AWS_ACCOUNT_ID: ""

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew
      - ./gradlew clean
  pre_build:
    commands:
      - echo "Pre-build phase starting ..."
      - echo "Logging in to the Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Build phase starting ..."
      - echo "Starting PostgreSQL Docker container for tests ..."
      - |
        ECR_POSTGRES_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_PREFIX/library/postgres:$POSTGRES_TAG"
        if ! docker pull "${ECR_POSTGRES_IMAGE}"; then
        echo "WARNING: Failed to pull ${ECR_POSTGRES_IMAGE}. Using local image if available."
        fi
        docker run --name postgres-test -e POSTGRES_PASSWORD="$DB_PASSWORD" -e POSTGRES_DB=testdb -e POSTGRES_USER=postgres -d "${ECR_POSTGRES_IMAGE}"
      - echo "Starting the Gradle testing task ..."
      - ./gradlew test
      - echo "Stopping PostgreSQL Docker container ..."
      - docker stop postgres-test
      - docker rm postgres-test
      - echo "Building Docker image ..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo "Tagging Docker image ..."
      - docker tag roleplay-academy-api:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/roleplay-academy-api:latest
      - echo "Build phase completed"
  post_build:
    commands:
      - echo "Post-build phase starting ..."
      - echo "Pushing Docker image to ECR ..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/roleplay-academy-api:latest
      - echo "Post-build phase completed"

artifacts:
  files:
    - build/libs/**/*.jar
  discard-paths: yes