version: 0.2

env:
  variables:
    POSTGRES_TAG: 16.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew
      - ./gradlew clean
  pre_build:
    commands:
      - echo "Pre-build phase starting ..."
      - ./gradlew compileJava
      - echo "Logging in to the Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Build phase starting ..."
      - ./gradlew build
      - echo "Build phase completed"
  post_build:
    commands:
      - echo "Post-build phase starting ..."
      - echo "Starting PostgreSQL Docker container for tests..."
      - ECR_POSTGRES_IMAGE=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_PREFIX/library/postgres:$POSTGRES_TAG
      - docker pull ${ECR_POSTGRES_IMAGE} || true
      - docker run --name postgres-test -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=testdb -e POSTGRES_USER=postgres -d ${ECR_POSTGRES_IMAGE}
      - ./gradlew test
      - echo "Stopping PostgreSQL Docker container..."
      - docker stop postgres-test
      - docker rm postgres-test

artifacts:
  files:
    - build/libs/**/*.jar
  discard-paths: yes