version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - chmod +x ./gradlew
      - ./gradlew clean
  pre_build:
    commands:
      - echo "Pre-build phase starting ..."
      - ./gradlew compileJava
      - echo "Pre-build phase completed"
  build:
    commands:
      - echo "Build phase starting ..."
      - ./gradlew build
      - echo "Build phase completed"
  post_build:
    commands:
      - echo "Post-build phase starting ..."
      - echo "Starting PostgreSQL Docker container for tests..."
      - docker run --name postgres-test -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=testdb -e POSTGRES_USER=postgres -d postgres:16.2
      - ./gradlew test
      - echo "Stopping PostgreSQL Docker container..."
      - docker stop postgres-test
      - docker rm postgres-test

artifacts:
  files:
    - build/libs/**/*.jar
  discard-paths: yes