services:
  postgres:
    image: 'postgres:16.2'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  spring-api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - 'SPRING_PROFILES_ACTIVE=local'
      - 'DB_NAME=${POSTGRES_DB}'
      - 'DB_USER=${POSTGRES_USER}'
      - 'DB_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080/actuator/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5