services:
  mysql:
    image: 'mysql:8.0.36'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
  spring-api:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - 'SPRING_PROFILES_ACTIVE=local'
      - 'DB_NAME=${MYSQL_DATABASE}'
      - 'DB_USER=${MYSQL_USER}'
      - 'DB_PASSWORD=${MYSQL_PASSWORD}'
    ports:
      - '8080:8080'
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8080/actuator/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5