services:
  mysql:
    image: 'mysql:8.0.36'
    environment:
      - 'MYSQL_DATABASE=${MYSQL_DATABASE}'
      - 'MYSQL_PASSWORD=${MYSQL_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'MYSQL_USER=${MYSQL_USER}'
    ports:
      - '3306:3306'
  spring-api:
    build: .
    depends_on:
      - mysql
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
    ports:
      - '8080:8080'