spring:
  application:
    profiles:
      active: local
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    user: ${LIQUIBASE_USER}
    password: ${LIQUIBASE_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health, info, liquibase
logging:
  level:
    org.liquibase: DEBUG