spring:
  application:
    name: roleplayacademyapi
    profiles:
      active: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
server:
    port: 8080
    error:
        include-message: always
    servlet:
        context-path: /api
        load-time:
            enabled: true
logging:
    level:
      org.springframework: INFO
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      com.zaxxer.hikari: INFO
      org.liquibase: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      enabled: true