spring:
  application:
    name: roleplayacademyapi
    profiles:
      active: dev
  datasource:
    url: jdbc:postgresql://postgres:5432/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
server:
    port: 8080
    error:
        include-message: always
    servlet:
        context-path: /api
        load-time:
            enabled: true
logging:
    level:
        org.springframework: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        com.zaxxer.hikari: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      enabled: true