name: AWS Self-Hosted - CI Build
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-aws-codebuild-ci-build:
    runs-on: self-hosted
    steps:
      - name: Run AWS Codebuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
            project-name: codebuild-roleplay-academy-api-ci-${{ github.run_id }}-${{ github.run_attempt }}
            source-version: ${{ github.sha }}
            environment-variables-override: name=GITHUB_REF,value=${{ github.ref }}
            buildspec-override: buildspec-ci.yml
        env:
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}