name: GitHub Action - CI Build
on:
  pull_request:
      types: [opened, synchronize, reopened]

permissions:
  id-token: write
  contents: read

jobs:
  run-codebuild-roleplay-academy-api-github-action-ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          mask-aws-account-id: true

      - name: Run AWS CodeBuild
        id: start_build
        run: |
            BUILD_ID=$(aws codebuild start-build \
                --project-name roleplay-academy-api-github-action-ci \
                --source-version ${{ github.sha }} \
                --environment-variables-override name=GITHUB_REF,value=${{ github.ref }} \
                --buildspec-override buildspec-ci.yml \
                --query 'build.id' \
                --output text)
            echo "BUILD_ID=$BUILD_ID" >> $GITHUB_ENV

      - name: Log started build
        run: echo "Started build with ID.. ${{ env.BUILD_ID }}"

      - name: Wait for CodeBuild to complete
        run: aws codebuild wait build-complete --ids ${{ env.BUILD_ID }}
