name: CI Build
on: [push]
jobs:
  run-aws-codebuild-ci-build:
    runs-on: self-hosted
    steps:
      - name: Run AWS Codebuild
        run: |
          echo "Starting AWS CodeBuild with buildspec.yml..."
          aws codebuild start-build \
            --project-name codebuild-roleplay-academy-api-ci-${{ github.run_id }}-${{ github.run_attempt }} \
            --source-version ${{ github.sha }} \
            --environment-variables-override name=GITHUB_REF,value=${{ github.ref }} \
            --buildspec-override buildspec-ci.yml