name: CI Build
on:
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  run-codebuild-roleplay-academy-api-github-action-ci-job:
    runs-on:
      - codebuild-roleplay-academy-api-github-action-ci-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World"